//! `Charts.md` in the vault: `chart` code blocks for the Obsidian **Charts**
//! community plugin (phibr0/obsidian-charts), regenerated from the ledger
//! whenever it changes. The plugin renders the YAML inside each block, so the
//! bot only has to keep the numbers current — no JS, works on mobile.
//!
//! Generated file: do not edit; put custom charts in another note.

use crate::finance::Txn;
use chrono::{Datelike, Duration, NaiveDate, Utc};
use std::collections::BTreeMap;

pub const FILE: &str = "Charts.md";

fn today() -> NaiveDate {
    let tz = std::env::var("DEFAULT_TZ").unwrap_or_else(|_| "UTC".into());
    match tz.parse::<chrono_tz::Tz>() {
        Ok(tz) => Utc::now().with_timezone(&tz).date_naive(),
        Err(_) => Utc::now().date_naive(),
    }
}

fn parse_date(s: &str) -> Option<NaiveDate> {
    NaiveDate::parse_from_str(s.get(..10)?, "%Y-%m-%d").ok()
}

fn month_start(d: NaiveDate) -> NaiveDate {
    NaiveDate::from_ymd_opt(d.year(), d.month(), 1).unwrap_or(d)
}

fn prev_month(d: NaiveDate) -> NaiveDate {
    let (y, m) = if d.month() == 1 { (d.year() - 1, 12) } else { (d.year(), d.month() - 1) };
    NaiveDate::from_ymd_opt(y, m, 1).unwrap_or(d)
}

const MONTHS: [&str; 12] = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

fn month_label(d: NaiveDate) -> String {
    format!("{} {}", MONTHS[(d.month() - 1) as usize], d.year() % 100)
}

/// Net spend for a row: expenses count, refunds subtract, everything else 0.
fn spend(t: &Txn) -> f64 {
    match t.direction.as_str() {
        "Expense" => t.amount,
        "Refund" => -t.amount,
        _ => 0.0,
    }
}

fn income(t: &Txn) -> f64 {
    if t.direction == "Income" { t.amount } else { 0.0 }
}

fn r2(x: f64) -> f64 {
    (x * 100.0).round() / 100.0
}

fn yaml_str_list(items: &[String]) -> String {
    let q: Vec<String> = items.iter().map(|s| format!("\"{}\"", s.replace('"', "'"))).collect();
    format!("[{}]", q.join(", "))
}

fn yaml_num_list(items: &[f64]) -> String {
    let q: Vec<String> = items.iter().map(|x| format!("{}", r2(*x))).collect();
    format!("[{}]", q.join(", "))
}

struct Block {
    kind: &'static str,
    labels: Vec<String>,
    series: Vec<(String, Vec<f64>)>,
    extra: &'static str,
}

impl Block {
    fn render(&self) -> String {
        let mut s = format!("```chart\ntype: {}\nlabels: {}\nseries:\n", self.kind, yaml_str_list(&self.labels));
        for (title, data) in &self.series {
            s.push_str(&format!("  - title: \"{}\"\n    data: {}\n", title.replace('"', "'"), yaml_num_list(data)));
        }
        s.push_str(self.extra);
        s.push_str("```\n");
        s
    }
}

/// Build the whole note from the ledger.
pub fn render(txns: &[Txn]) -> String {
    let today = today();
    let this_month = month_start(today);
    let mut out = String::from(
        "---\ntitle: Charts\ntype: dashboard\n---\n\n\
         > [!info] Generated by Optimimer from the ledger — edits here are overwritten. Needs the **Charts** community plugin.\n\n",
    );

    // ---- 1. Income vs spending, last 12 months ----------------------------
    let mut months: Vec<NaiveDate> = Vec::new();
    let mut m = this_month;
    for _ in 0..12 {
        months.push(m);
        m = prev_month(m);
    }
    months.reverse();
    let first = months[0];
    let mut inc = vec![0.0; 12];
    let mut sp = vec![0.0; 12];
    for t in txns {
        let Some(d) = parse_date(&t.date) else { continue };
        if d < first {
            continue;
        }
        if let Some(i) = months.iter().position(|m| m.year() == d.year() && m.month() == d.month()) {
            inc[i] += income(t);
            sp[i] += spend(t);
        }
    }
    // Trim leading months with no data so a young ledger isn't mostly zeros.
    let start = (0..12).find(|&i| inc[i] > 0.0 || sp[i] > 0.0).unwrap_or(11);
    let labels: Vec<String> = months[start..].iter().map(|m| month_label(*m)).collect();
    let net: Vec<f64> = (start..12).map(|i| inc[i] - sp[i]).collect();
    out.push_str("## Income vs spending\n\n");
    out.push_str(
        &Block {
            kind: "bar",
            labels: labels.clone(),
            series: vec![("Income".into(), inc[start..].to_vec()), ("Spent".into(), sp[start..].to_vec())],
            extra: "beginAtZero: true\nlegend: true\nwidth: 100%\n",
        }
        .render(),
    );
    let _ = (labels, net);

    // ---- 1b. Money flow (Mermaid sankey), last 3 months with data --------
    out.push_str("\n## Money flow\n\n");
    let mut flows = 0;
    for m in months.iter().rev() {
        if flows == 3 {
            break;
        }
        let end = if m.month() == 12 {
            NaiveDate::from_ymd_opt(m.year() + 1, 1, 1).unwrap()
        } else {
            NaiveDate::from_ymd_opt(m.year(), m.month() + 1, 1).unwrap()
        };
        if let Some(block) = render_sankey(txns, *m, end) {
            out.push_str(&format!("### {}\n\n{block}\n", month_label(*m)));
            flows += 1;
        }
    }
    if flows == 0 {
        out.push_str("_No months with data yet._\n");
    }

    // ---- 2. Spending by category, this month (fallback: last month) --------
    let by_cat = |from: NaiveDate, to: NaiveDate| -> Vec<(String, f64)> {
        let mut map: BTreeMap<String, f64> = BTreeMap::new();
        for t in txns {
            let Some(d) = parse_date(&t.date) else { continue };
            if d < from || d >= to {
                continue;
            }
            let s = spend(t);
            if s != 0.0 {
                let cat = if t.category.is_empty() { "Other".to_string() } else { t.category.clone() };
                *map.entry(cat).or_default() += s;
            }
        }
        let mut v: Vec<(String, f64)> = map.into_iter().filter(|(_, a)| *a > 0.0).collect();
        v.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
        v
    };
    let next_month = if this_month.month() == 12 {
        NaiveDate::from_ymd_opt(this_month.year() + 1, 1, 1).unwrap()
    } else {
        NaiveDate::from_ymd_opt(this_month.year(), this_month.month() + 1, 1).unwrap()
    };
    // Walk back to the most recent month that has any expenses (the ledger
    // may lag behind the calendar while statements are pending).
    let mut m_start = this_month;
    let mut m_end = next_month;
    let mut cats = by_cat(m_start, m_end);
    for _ in 0..24 {
        if !cats.is_empty() {
            break;
        }
        m_end = m_start;
        m_start = prev_month(m_start);
        cats = by_cat(m_start, m_end);
    }
    // Heading stays fixed so `![[Charts.md#Spending by category]]` keeps working.
    out.push_str("\n## Spending by category\n\n");
    if cats.is_empty() {
        out.push_str("_No expenses yet._\n");
    } else {
        out.push_str(&format!("**{}**\n\n", month_label(m_start)));
        // Horizontal bars, not a doughnut: pie-type charts render on a square
        // canvas, which makes the embed twice as tall as it needs to be.
        out.push_str(
            &Block {
                kind: "bar",
                labels: cats.iter().map(|(c, _)| c.clone()).collect(),
                series: vec![("Spent".into(), cats.iter().map(|(_, a)| *a).collect())],
                extra: "indexAxis: y\nlabelColors: true\nbeginAtZero: true\nlegend: false\nwidth: 100%\n",
            }
            .render(),
        );
    }

    // ---- 3. Category trend, last 6 months, stacked ------------------------
    let six: Vec<NaiveDate> = months[6..].to_vec();
    let mut totals: BTreeMap<String, f64> = BTreeMap::new();
    let mut per: BTreeMap<String, Vec<f64>> = BTreeMap::new();
    for t in txns {
        let Some(d) = parse_date(&t.date) else { continue };
        let Some(i) = six.iter().position(|m| m.year() == d.year() && m.month() == d.month()) else { continue };
        let s = spend(t);
        if s == 0.0 {
            continue;
        }
        let cat = if t.category.is_empty() { "Other".to_string() } else { t.category.clone() };
        *totals.entry(cat.clone()).or_default() += s;
        per.entry(cat).or_insert_with(|| vec![0.0; 6])[i] += s;
    }
    let mut ranked: Vec<(String, f64)> = totals.into_iter().collect();
    ranked.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
    let top: Vec<String> = ranked.iter().take(6).map(|(c, _)| c.clone()).collect();
    let mut series: Vec<(String, Vec<f64>)> = top.iter().map(|c| (c.clone(), per[c].clone())).collect();
    let rest: Vec<f64> = (0..6)
        .map(|i| ranked.iter().skip(6).map(|(c, _)| per[c][i]).sum::<f64>())
        .collect();
    if rest.iter().any(|x| *x > 0.0) {
        series.push(("Everything else".into(), rest));
    }
    out.push_str("\n## Category trend — last 6 months\n\n");
    if series.is_empty() {
        out.push_str("_No expenses yet._\n");
    } else {
        out.push_str(
            &Block {
                kind: "bar",
                labels: six.iter().map(|m| month_label(*m)).collect(),
                series,
                extra: "stacked: true\nbeginAtZero: true\nlegend: true\nwidth: 100%\n",
            }
            .render(),
        );
    }

    // ---- 4. Daily spend, last 30 days ---------------------------------------
    let from = today - Duration::days(29);
    let mut daily = vec![0.0; 30];
    for t in txns {
        let Some(d) = parse_date(&t.date) else { continue };
        if d < from || d > today {
            continue;
        }
        daily[(d - from).num_days() as usize] += spend(t);
    }
    let labels: Vec<String> = (0..30).map(|i| (from + Duration::days(i)).format("%b %-d").to_string()).collect();
    out.push_str("\n## Daily spend — last 30 days\n\n");
    if daily.iter().all(|x| *x == 0.0) {
        out.push_str("_No expenses in the last 30 days._\n");
    } else {
        out.push_str(
            &Block {
                kind: "bar",
                labels,
                series: vec![("Spent".into(), daily)],
                extra: "beginAtZero: true\nlegend: false\nwidth: 100%\n",
            }
            .render(),
        );
    }
    out
}

/// Regenerate `Charts.md` in the vault from the whole ledger. Cheap (a few
/// hundred rows), so callers just invoke it after any ledger change.
pub fn refresh() {
    let txns = crate::finance::global().all();
    let path = crate::vault::dir().join(FILE);
    if let Err(e) = std::fs::write(&path, render(&txns)) {
        tracing::warn!("charts: could not write {}: {e}", path.display());
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn t(date: &str, amount: f64, dir: &str, cat: &str) -> Txn {
        Txn { date: date.into(), amount, direction: dir.into(), category: cat.into(), ..Default::default() }
    }

    #[test]
    fn renders_four_sections_with_chart_blocks() {
        let today = today();
        let d = today.format("%Y-%m-%d").to_string();
        let rows = vec![
            t(&d, 40.0, "Expense", "Groceries"),
            t(&d, 10.0, "Refund", "Groceries"),
            t(&d, 3000.0, "Income", "Salary"),
            t(&d, 25.0, "Expense", "Dining"),
            t(&d, 500.0, "Transfer", "Transfer"),
        ];
        let md = render(&rows);
        assert_eq!(md.matches("```chart").count(), 4, "{md}");
        assert!(md.contains("sankey-beta"), "{md}");
        assert!(md.contains("indexAxis: y"));
        assert!(md.contains("stacked: true"));
        // refund nets against groceries: 30, dining 25; transfer ignored
        assert!(md.contains("labels: [\"Groceries\", \"Dining\"]"), "{md}");
        assert!(md.contains("data: [30, 25]"), "{md}");
        assert!(md.contains("data: [3000]"), "income series\n{md}");
    }

    #[test]
    fn empty_ledger_degrades_gracefully() {
        let md = render(&[]);
        assert!(md.contains("_No expenses yet._"));
        assert!(md.contains("```chart\ntype: bar"), "monthly chart still emitted");
    }
}

// ---------------------------------------------------------------------------
// Money flow (Mermaid sankey)
// ---------------------------------------------------------------------------

/// Sankey node names: commas would split the CSV row, quotes end the name.
fn sankey_name(s: &str) -> String {
    s.replace([',', '"', '\n'], " ").trim().to_string()
}

/// One month's flow: Salary / Other income / Transfers in → Income → expense
/// categories, Savings, Transfers out, and either "Unallocated" (surplus) or a
/// "From savings / credit" node covering the shortfall. Card payments are left
/// out: the purchases they settle are already in the expense categories.
/// Returns `None` when the month has nothing to show.
pub fn render_sankey(txns: &[Txn], from: NaiveDate, to: NaiveDate) -> Option<String> {
    let mut income_src: BTreeMap<String, f64> = BTreeMap::new();
    let mut cats: BTreeMap<String, f64> = BTreeMap::new();
    let mut transfers: BTreeMap<String, f64> = BTreeMap::new();
    for t in txns {
        let Some(d) = parse_date(&t.date) else { continue };
        if d < from || d >= to {
            continue;
        }
        let cat = if t.category.is_empty() { "Other".to_string() } else { t.category.clone() };
        match t.direction.as_str() {
            "Income" => {
                let src = if cat.eq_ignore_ascii_case("Salary") { "Salary".to_string() } else { "Other income".to_string() };
                *income_src.entry(src).or_default() += t.amount;
            }
            "Expense" => *cats.entry(cat).or_default() += t.amount,
            "Refund" => *cats.entry(cat).or_default() -= t.amount,
            "Transfer" => match cat.to_lowercase().as_str() {
                "transfer in" => *income_src.entry("Transfers in".to_string()).or_default() += t.amount,
                "savings" => *transfers.entry("Savings".to_string()).or_default() += t.amount,
                "transfer out" => *transfers.entry("Transfers out".to_string()).or_default() += t.amount,
                _ => {} // card payments (and legacy "Transfer") — already counted as spending
            },
            _ => {}
        }
    }
    let cats: Vec<(String, f64)> = cats.into_iter().filter(|(_, a)| *a > 0.005).collect();
    let income_total: f64 = income_src.values().sum();
    let out_total: f64 = cats.iter().map(|(_, a)| a).sum::<f64>() + transfers.values().sum::<f64>();
    if income_total <= 0.0 && out_total <= 0.0 {
        return None;
    }

    let mut rows: Vec<String> = Vec::new();
    for (src, a) in &income_src {
        rows.push(format!("{},Income,{}", sankey_name(src), r2(*a)));
    }
    let gap = out_total - income_total;
    if gap > 0.005 {
        rows.push(format!("From savings / credit,Income,{}", r2(gap)));
    }
    let mut sorted = cats.clone();
    sorted.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
    for (cat, a) in &sorted {
        rows.push(format!("Income,{},{}", sankey_name(cat), r2(*a)));
    }
    for (label, a) in &transfers {
        if *a > 0.005 {
            rows.push(format!("Income,{},{}", sankey_name(label), r2(*a)));
        }
    }
    if gap < -0.005 {
        rows.push(format!("Income,Unallocated,{}", r2(-gap)));
    }
    Some(format!(
        "```mermaid\n%%{{init: {{\"sankey\": {{\"showValues\": true, \"linkColor\": \"gradient\", \"nodeAlignment\": \"justify\"}}}}}}%%\nsankey-beta\n\n{}\n```\n",
        rows.join("\n")
    ))
}

#[cfg(test)]
mod sankey_tests {
    use super::*;

    fn t(date: &str, amount: f64, dir: &str, cat: &str) -> Txn {
        Txn { date: date.into(), amount, direction: dir.into(), category: cat.into(), ..Default::default() }
    }

    #[test]
    fn flow_balances_with_surplus_and_shortfall() {
        let from = NaiveDate::from_ymd_opt(2026, 6, 1).unwrap();
        let to = NaiveDate::from_ymd_opt(2026, 7, 1).unwrap();
        let rows = vec![
            t("2026-06-02", 3000.0, "Income", "Salary"),
            t("2026-06-03", 200.0, "Income", "Income"),
            t("2026-06-10", 500.0, "Expense", "Dining, fancy"),
            t("2026-06-11", 50.0, "Refund", "Dining, fancy"),
            t("2026-06-12", 1000.0, "Transfer", "Savings"),
            t("2026-06-13", 250.0, "Transfer", "Transfer in"),
            t("2026-06-14", 999.0, "Transfer", "Card payment"),
            t("2026-06-15", 999.0, "Transfer", "Transfer"),
        ];
        let md = render_sankey(&rows, from, to).unwrap();
        assert!(md.contains("Salary,Income,3000"), "{md}");
        assert!(md.contains("Other income,Income,200"), "{md}");
        assert!(md.contains("Income,Dining  fancy,450"), "refund netted, comma stripped\n{md}");
        assert!(md.contains("Transfers in,Income,250"), "{md}");
        assert!(md.contains("Income,Savings,1000"), "{md}");
        assert!(md.contains("Income,Unallocated,2000"), "3450 in - 450 - 1000\n{md}");
        assert!(!md.contains("999"), "card payments excluded\n{md}");
        assert!(!md.contains("From savings"), "{md}");

        let short = vec![t("2026-06-02", 100.0, "Income", "Salary"), t("2026-06-10", 400.0, "Expense", "Rent")];
        let md = render_sankey(&short, from, to).unwrap();
        assert!(md.contains("From savings / credit,Income,300"), "{md}");
        assert!(render_sankey(&[], from, to).is_none());
    }
}

// ---------------------------------------------------------------------------
// Gantt (Mermaid, built in to Obsidian — no plugin)
// ---------------------------------------------------------------------------

pub const GANTT_FILE: &str = "Gantt.md";

/// Words the (case-insensitive) gantt lexer treats as keywords at the start of
/// a line. A task called "Call dentist" would otherwise put it in callback mode.
const GANTT_KEYWORDS: &[&str] = &[
    "call", "click", "section", "title", "gantt", "dateformat", "axisformat", "tickinterval", "includes",
    "excludes", "todaymarker", "inclusiveenddates", "topaxis", "weekday", "weekend", "acctitle", "accdescr",
    "accdescription",
];

/// Mermaid gantt task names can't carry `:` or `#`, `;` ends a statement, and a
/// leading keyword changes the lexer state — so those get a bullet prefix.
fn mermaid_name(s: &str) -> String {
    let mut n: String = s.chars().map(|c| if matches!(c, ':' | '#' | ';' | '\n') { '-' } else { c }).collect();
    let first = n.trim().split_whitespace().next().unwrap_or("").to_lowercase();
    if GANTT_KEYWORDS.contains(&first.as_str()) || n.trim_start().starts_with("%%") {
        n = format!("· {}", n.trim_start());
    }
    if n.len() > 30 {
        let mut cut = 30;
        while !n.is_char_boundary(cut) {
            cut -= 1;
        }
        n.truncate(cut);
        n.push('…');
    }
    n.trim().to_string()
}

/// Render the timeline note from task docs. Bars run from the task's `created`
/// day to its `due` day; done tasks are greyed, overdue open tasks are marked
/// critical. Done tasks older than two weeks and undated tasks stay out of the
/// chart (the latter are listed beneath it).
pub fn render_gantt(tasks: &[crate::vault::Doc]) -> String {
    let today = today();
    let cutoff = today - Duration::days(14);
    let mut sections: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut undated: Vec<String> = Vec::new();
    let mut shown = 0;
    for d in tasks {
        let status = d.str("status").to_lowercase();
        let done = status == "done";
        let title = mermaid_name(&d.title());
        let due = parse_date(&d.str("due"));
        if done {
            let completed = parse_date(&d.str("completed")).or(due);
            if completed.map(|c| c < cutoff).unwrap_or(true) {
                continue;
            }
        }
        let Some(due) = due else {
            if !done {
                undated.push(d.title());
            }
            continue;
        };
        let start = parse_date(&d.created()).unwrap_or(due).min(due);
        // A same-day task still needs a visible bar.
        let end = if start == due { due + Duration::days(1) } else { due };
        let tag = if done {
            "done, "
        } else if due < today {
            "crit, "
        } else if status == "doing" {
            "active, "
        } else {
            ""
        };
        // Section = category, or "Category · Project" when the task has one;
        // the bar label is just the (shortened) title so it fits the bar.
        let cat = { let c = d.str("category"); if c.is_empty() { "Uncategorised".to_string() } else { c } };
        let project = d.str("project");
        let section = if project.is_empty() { cat } else { format!("{cat} · {project}") };
        sections.entry(section).or_default().push(format!("    {title} :{tag}{start}, {end}"));
        shown += 1;
    }

    // No heading of its own: Home.md embeds the whole note, and a section embed
    // would repeat the heading. Provenance goes in frontmatter instead.
    let mut out = String::from("---\ntitle: Gantt\ntype: dashboard\ngenerated: Optimimer — from tasks/, do not edit; bars run created→due, red = overdue\n---\n\n");
    if shown == 0 {
        out.push_str("_No dated tasks yet. Give a task a date (\"/todo dentist tuesday 2pm\") and it appears here._\n");
    } else {
        // No `todayMarker` styling: the gantt lexer cuts that token at `#`, so a hex
        // colour breaks the whole diagram. The default marker is drawn anyway.
        out.push_str("```mermaid\ngantt\n    title Tasks\n    dateFormat YYYY-MM-DD\n    axisFormat %b %d\n    tickInterval 1day\n");
        for (name, rows) in &sections {
            out.push_str(&format!("    section {}\n", mermaid_name(name)));
            for r in rows {
                out.push_str(r);
                out.push('\n');
            }
        }
        out.push_str("```\n");
    }
    if !undated.is_empty() {
        out.push_str("\n## Undated\n\n");
        for t in undated {
            out.push_str(&format!("- [ ] {t}\n"));
        }
    }
    out
}

/// Regenerate `Gantt.md` from the vault's task files.
pub fn refresh_gantt() {
    let tasks = crate::vault::list(crate::vault::TASKS);
    let path = crate::vault::dir().join(GANTT_FILE);
    if let Err(e) = std::fs::write(&path, render_gantt(&tasks)) {
        tracing::warn!("gantt: could not write {}: {e}", path.display());
    }
}

/// Background refresh so tasks edited directly in Obsidian reach the chart.
pub async fn run_gantt_worker() {
    let secs = std::env::var("GANTT_REFRESH_SECS").ok().and_then(|s| s.parse().ok()).unwrap_or(600u64);
    loop {
        tokio::time::sleep(std::time::Duration::from_secs(secs.max(30))).await;
        refresh_gantt();
    }
}

#[cfg(test)]
mod gantt_tests {
    use super::*;
    use crate::vault::Doc;
    use serde_json::Value;

    fn task(title: &str, status: &str, created: &str, due: &str, project: &str) -> Doc {
        let mut d = Doc::default();
        d.set("title", Value::String(title.into()));
        d.set("category", Value::String(if project.is_empty() { "Admin".into() } else { "Social".into() }));
        d.set("status", Value::String(status.into()));
        d.set("created", Value::String(created.into()));
        d.set("due", if due.is_empty() { Value::Null } else { Value::String(due.into()) });
        d.set("project", if project.is_empty() { Value::Null } else { Value::String(project.into()) });
        d
    }

    #[test]
    fn gantt_sections_tags_and_undated() {
        let t = today();
        let past = (t - Duration::days(3)).format("%Y-%m-%d").to_string();
        let future = (t + Duration::days(3)).format("%Y-%m-%dT14:00").to_string();
        let docs = vec![
            task("Call Sam: venue", "todo", &past, &future, "Wedding"),
            task("Old thing", "todo", &past, &past, ""),
            task("Someday", "todo", &past, "", ""),
        ];
        let md = render_gantt(&docs);
        assert!(md.contains("section Social · Wedding"), "project in section\n{md}");
        assert!(md.contains("section Admin"), "{md}");
        assert!(md.contains("· Call Sam- venue :"), "colon escaped\n{md}");
        assert!(!md.contains("\n    Call Sam"), "no task line may start with a lexer keyword\n{md}");
        assert!(md.contains("Old thing :crit, "), "overdue is crit\n{md}");
        assert!(md.contains("- [ ] Someday"), "undated listed\n{md}");
        assert!(!md.contains("Someday :"), "undated not charted");
    }
}
