#!/usr/bin/env bash
# Interactive installer for the optimimer backend. Runs ON the target Pi —
# normally invoked for you by `make deploy PI=user@host`, but you can also run it
# directly on the Pi after the files are in /opt/optimimer:
#   /opt/optimimer/install.sh
#
# Auto-detection: any value already present in the environment is used as-is and
# NOT prompted for. So if your host (or Infisical) already exports the keys, run:
#   infisical run --env=prod -- /opt/optimimer/install.sh
# and the installer skips straight past the questions it already has answers to.
#
# The Telegram bot uses long-polling, so no inbound ports are opened.
set -euo pipefail

APP=optimimer
DIR=/opt/$APP
SERVICE=/etc/systemd/system/$APP.service
BIN="$DIR/optimimer-backend"
ENV_FILE="$DIR/optimimer.env"
RUN_USER="$(id -un)"

echo
echo "=== Optimimer installer ==="
echo "install dir:  $DIR"
echo "service user: $RUN_USER"
echo

if [ ! -x "$BIN" ]; then
  if [ -f "$BIN" ]; then chmod +x "$BIN"; else
    echo "!! $BIN not found — copy the aarch64 binary there first (make deploy does this)." >&2
    exit 1
  fi
fi

# ---- reuse non-secret config from a previous install -------------------------
# Timezone and the two Category labels aren't secrets, so Infisical doesn't inject
# them — without this, every re-deploy would re-prompt for them. Pull whatever the
# last install wrote into the env file (unless already set in the environment) so
# `ask` finds them and stays quiet. First install (no env file) still prompts.
if [ -f "$ENV_FILE" ]; then
  for v in DEFAULT_TZ CATEGORY_A CATEGORY_B; do
    if [ -z "${!v:-}" ]; then
      prev="$(sed -n "s/^$v=//p" "$ENV_FILE" | tail -1)"
      [ -n "$prev" ] && export "$v=$prev"
    fi
  done
fi

# ---- what's already in the environment? --------------------------------------
detected=0
for v in TELEGRAM_BOT_TOKEN TELEGRAM_ALLOWED_CHAT_IDS OPENROUTER_API_KEY NOTION_TOKEN DEFAULT_TZ CATEGORY_A CATEGORY_B \
         LIFEOS_DB_ID NOTES_DB_ID TOPICS_DB_ID AREAS_DB_ID PROJECTS_DB_ID FINANCES_DB_ID RENT_AMOUNTS RESEND_API_KEY EMAIL_FROM; do
  if [ -n "${!v:-}" ]; then echo "  ✓ $v detected in environment — will not prompt for it"; detected=1; fi
done
[ "$detected" = 0 ] && echo "  (no known vars in the environment — will prompt for them)"
echo

# ---- secret strategy: capture to disk, or inject via Infisical at runtime -----
WRAP_INFISICAL=n
INFISICAL_ENV=prod
if command -v infisical >/dev/null 2>&1; then
  read -r -p "infisical CLI found. Inject secrets at RUNTIME via 'infisical run' (nothing on disk)? [y/N] " a
  if [[ "${a:-}" =~ ^[Yy] ]]; then
    WRAP_INFISICAL=y
    read -r -p "  Infisical environment slug [prod]: " INFISICAL_ENV; INFISICAL_ENV="${INFISICAL_ENV:-prod}"
  fi
fi

# Use an existing env value if set, otherwise prompt. `ask` is visible, `asks` hidden.
ask() {
  local var="$1" label="$2" def="${3:-}"
  if [ -n "${!var:-}" ]; then printf '%s' "${!var}"; return; fi
  local val; read -r -p "  $label${def:+ [$def]}: " val </dev/tty; printf '%s' "${val:-$def}"
}
asks() {
  local var="$1" label="$2"
  if [ -n "${!var:-}" ]; then printf '%s' "${!var}"; return; fi
  local val; read -rs -p "  $label (blank to skip): " val </dev/tty; echo >&2; printf '%s' "$val"
}

# ---- gather config -----------------------------------------------------------
reuse=n
if [ -f "$ENV_FILE" ] && [ "$WRAP_INFISICAL" = n ] && [ "$detected" = 0 ]; then
  read -r -p "$ENV_FILE exists. Reuse it as-is? [Y/n] " reuse; reuse="${reuse:-Y}"
fi

if [[ ! "$reuse" =~ ^[Yy] ]]; then
  TZ_IN="$(ask DEFAULT_TZ 'Default timezone (IANA, e.g. Europe/London)' UTC)"
  CATA="$(ask CATEGORY_A 'Category A label' Sagemesh)"
  CATB="$(ask CATEGORY_B 'Category B label' Personal)"

  umask 077
  if [ "$WRAP_INFISICAL" = y ]; then
    # Secrets are injected fresh at every service start — only non-secret config
    # is persisted here.
    cat > "$ENV_FILE" <<EOF
# Non-secret config. Secrets are injected at runtime by 'infisical run'.
DEFAULT_TZ=$TZ_IN
CATEGORY_A=$CATA
CATEGORY_B=$CATB
# Comma-separated Telegram chat ids allowed to use the bot. REQUIRED — the bot
# denies everyone if this is empty. Message the bot once and read the
# 'unauthorized chat <id>' line in the logs to find your id.
TELEGRAM_ALLOWED_CHAT_IDS=${TELEGRAM_ALLOWED_CHAT_IDS:-}
EOF
  else
    TG="$(asks TELEGRAM_BOT_TOKEN 'Telegram bot token (from @BotFather)')"
    OR="$(asks OPENROUTER_API_KEY 'OpenRouter API key')"
    NOTION="$(asks NOTION_TOKEN 'Notion token (optional)')"
    cat > "$ENV_FILE" <<EOF
# Generated by deploy/install.sh — keep private (chmod 600). Re-run to change.
DEFAULT_TZ=$TZ_IN
TELEGRAM_BOT_TOKEN=$TG
# Comma-separated Telegram chat ids allowed to use the bot. REQUIRED — the bot
# denies everyone if empty. Message the bot, then read the 'unauthorized chat
# <id>' log line to find your id, and set it here (or in Infisical).
TELEGRAM_ALLOWED_CHAT_IDS=${TELEGRAM_ALLOWED_CHAT_IDS:-}
OPENROUTER_API_KEY=$OR
NOTION_TOKEN=$NOTION
CATEGORY_A=$CATA
CATEGORY_B=$CATB
# Notion database ids (optional). Carried through if already in the environment
# — e.g. via 'make deploy INFISICAL_ENV=dev'. Leave blank to save captures to
# disk instead of Notion. /todo needs LIFEOS_DB_ID (+ PROJECTS_DB_ID to attach a
# Project for calendar sync); /note needs NOTES_DB_ID.
LIFEOS_DB_ID=${LIFEOS_DB_ID:-}
NOTES_DB_ID=${NOTES_DB_ID:-}
TOPICS_DB_ID=${TOPICS_DB_ID:-}
AREAS_DB_ID=${AREAS_DB_ID:-}
PROJECTS_DB_ID=${PROJECTS_DB_ID:-}
# Finances DB (/spent, /earned, /balance, CSV import). Blank = transactions saved to disk.
FINANCES_DB_ID=${FINANCES_DB_ID:-}
# Exact e-transfer amounts treated as rent → Housing expense (comma-separated).
# Optional; rent detection is off unless you set this.
RENT_AMOUNTS=${RENT_AMOUNTS:-}
RESEND_API_KEY=${RESEND_API_KEY:-}
EMAIL_FROM=${EMAIL_FROM:-}
EOF
  fi
  chmod 600 "$ENV_FILE"
  echo "Wrote $ENV_FILE (0600)."
fi

# ---- ExecStart ---------------------------------------------------------------
if [ "$WRAP_INFISICAL" = y ]; then
  EXECSTART="$(command -v infisical) run --env=$INFISICAL_ENV --silent -- $BIN"
  echo
  echo "Service will start via:  infisical run --env=$INFISICAL_ENV -- optimimer-backend"
  echo "For headless auth, give it a machine identity token — e.g. add a drop-in:"
  echo "  sudo systemctl edit $APP   # then:  [Service]  Environment=INFISICAL_TOKEN=<token>"
else
  EXECSTART="$BIN"
fi

# ---- systemd unit ------------------------------------------------------------
echo "Installing systemd service ($SERVICE)…"
sudo tee "$SERVICE" >/dev/null <<EOF
[Unit]
Description=Optimimer backend (Telegram bot + scheduler)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$RUN_USER
WorkingDirectory=$DIR
EnvironmentFile=-$ENV_FILE
ExecStart=$EXECSTART
Restart=always
RestartSec=5
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable "$APP" >/dev/null 2>&1 || true
sudo systemctl restart "$APP"
sleep 1
sudo systemctl --no-pager status "$APP" | head -10 || true
echo
echo "Done. Follow logs with:  journalctl -u $APP -f"
