#!/usr/bin/env bash
# Interactive installer for the optimimer backend. Runs ON the target Pi —
# normally invoked for you by `make deploy PI=user@host`, but you can also run it
# directly on the Pi after the files are in /opt/optimimer:
#   /opt/optimimer/install.sh
#
# Auto-detection: any value already present in the environment is used as-is and
# NOT prompted for. So if your host (or Infisical) already exports the keys, run:
#   infisical run --env=prod -- /opt/optimimer/install.sh
# and the installer skips straight past the questions it already has answers to.
#
# Nothing personal is baked into the binary: the installer only collects the
# secrets and a default timezone, then prints a one-time SETUP CODE. Sending that
# code to the bot from Telegram pairs your account as the owner and starts the
# in-chat setup (name, timezone, categories, machines). Everything else is
# configured by talking to the bot.
#
# The Telegram bot uses long-polling, so no inbound ports are opened.
set -euo pipefail

APP=optimimer
DIR=/opt/$APP
SERVICE=/etc/systemd/system/$APP.service
BIN="$DIR/optimimer-backend"
ENV_FILE="$DIR/optimimer.env"
RUN_USER="$(id -un)"

echo
echo "=== Optimimer installer ==="
echo "install dir:  $DIR"
echo "service user: $RUN_USER"
echo

if [ ! -x "$BIN" ]; then
  if [ -f "$BIN" ]; then chmod +x "$BIN"; else
    echo "!! $BIN not found — copy the aarch64 binary there first (make deploy does this)." >&2
    exit 1
  fi
fi

# ---- reuse non-secret config from a previous install -------------------------
# The timezone, vault path and setup code aren't secrets, so Infisical doesn't
# inject them — without this, every re-deploy would re-prompt (or mint a new
# code). Pull whatever the last install wrote into the env file, unless the
# environment already has it. First install (no env file) still prompts.
if [ -f "$ENV_FILE" ]; then
  for v in DEFAULT_TZ VAULT_DIR OPTIMIMER_SETUP_CODE; do
    if [ -z "${!v:-}" ]; then
      prev="$(sed -n "s/^$v=//p" "$ENV_FILE" | tail -1)"
      [ -n "$prev" ] && export "$v=$prev"
    fi
  done
fi

# ---- what's already in the environment? --------------------------------------
detected=0
for v in TELEGRAM_BOT_TOKEN OPENROUTER_API_KEY DEFAULT_TZ VAULT_DIR OPTIMIMER_SETUP_CODE \
         TELEGRAM_ALLOWED_CHAT_IDS RENT_AMOUNTS RESEND_API_KEY EMAIL_FROM; do
  if [ -n "${!v:-}" ]; then echo "  ✓ $v detected in environment — will not prompt for it"; detected=1; fi
done
[ "$detected" = 0 ] && echo "  (no known vars in the environment — will prompt for them)"
echo

# ---- secret strategy: capture to disk, or inject via Infisical at runtime -----
WRAP_INFISICAL=n
INFISICAL_ENV=prod
if command -v infisical >/dev/null 2>&1; then
  read -r -p "infisical CLI found. Inject secrets at RUNTIME via 'infisical run' (nothing on disk)? [y/N] " a </dev/tty
  if [[ "${a:-}" =~ ^[Yy] ]]; then
    WRAP_INFISICAL=y
    read -r -p "  Infisical environment slug [prod]: " INFISICAL_ENV </dev/tty; INFISICAL_ENV="${INFISICAL_ENV:-prod}"
  fi
fi

# Use an existing env value if set, otherwise prompt. `ask` is visible, `asks` hidden.
ask() {
  local var="$1" label="$2" def="${3:-}"
  if [ -n "${!var:-}" ]; then printf '%s' "${!var}"; return; fi
  local val; read -r -p "  $label${def:+ [$def]}: " val </dev/tty; printf '%s' "${val:-$def}"
}
asks() {
  local var="$1" label="$2"
  if [ -n "${!var:-}" ]; then printf '%s' "${!var}"; return; fi
  local val; read -rs -p "  $label (blank to skip): " val </dev/tty; echo >&2; printf '%s' "$val"
}

# A short pairing code without look-alike characters (no 0/O/1/I), e.g. K7QD-3MXP.
gen_code() {
  local raw; raw="$(LC_ALL=C tr -dc 'A-HJ-NP-Z2-9' </dev/urandom | head -c 8)"
  printf '%s-%s' "${raw:0:4}" "${raw:4:4}"
}

# ---- gather config -----------------------------------------------------------
reuse=n
if [ -f "$ENV_FILE" ] && [ "$WRAP_INFISICAL" = n ] && [ "$detected" = 0 ]; then
  read -r -p "$ENV_FILE exists. Reuse it as-is? [Y/n] " reuse </dev/tty; reuse="${reuse:-Y}"
fi

SETUP_CODE="${OPTIMIMER_SETUP_CODE:-$(gen_code)}"

if [[ ! "$reuse" =~ ^[Yy] ]]; then
  TZ_IN="$(ask DEFAULT_TZ 'Default timezone (IANA, e.g. Europe/London)' UTC)"

  umask 077
  if [ "$WRAP_INFISICAL" = y ]; then
    # Secrets are injected fresh at every service start — only non-secret config
    # is persisted here.
    cat > "$ENV_FILE" <<EOF2
# Non-secret config. Secrets are injected at runtime by 'infisical run'.
DEFAULT_TZ=$TZ_IN
# One-time pairing code: send it to the bot from Telegram to become its owner.
OPTIMIMER_SETUP_CODE=$SETUP_CODE
VAULT_DIR=${VAULT_DIR:-$DIR/vault}
# Optional static allowlist of chat ids (pairing via codes is the normal path).
TELEGRAM_ALLOWED_CHAT_IDS=${TELEGRAM_ALLOWED_CHAT_IDS:-}
EOF2
  else
    TG="$(asks TELEGRAM_BOT_TOKEN 'Telegram bot token (from @BotFather)')"
    OR="$(asks OPENROUTER_API_KEY 'OpenRouter API key')"
    cat > "$ENV_FILE" <<EOF2
# Generated by deploy/install.sh — keep private (chmod 600). Re-run to change.
DEFAULT_TZ=$TZ_IN
TELEGRAM_BOT_TOKEN=$TG
OPENROUTER_API_KEY=$OR
# One-time pairing code: send it to the bot from Telegram to become its owner.
# The bot then walks you through the rest (name, timezone, categories, machines).
OPTIMIMER_SETUP_CODE=$SETUP_CODE
# Optional static allowlist of chat ids (pairing via codes is the normal path).
TELEGRAM_ALLOWED_CHAT_IDS=${TELEGRAM_ALLOWED_CHAT_IDS:-}
# Markdown vault: tasks, notes and summaries are written here as .md files. Point
# it at the folder Obsidian syncs (Obsidian Sync / Syncthing) so they show up everywhere.
VAULT_DIR=${VAULT_DIR:-$DIR/vault}
# Exact e-transfer amounts treated as rent → Housing expense (comma-separated).
# Optional; rent detection is off unless you set this.
RENT_AMOUNTS=${RENT_AMOUNTS:-}
RESEND_API_KEY=${RESEND_API_KEY:-}
EMAIL_FROM=${EMAIL_FROM:-}
EOF2
  fi
  chmod 600 "$ENV_FILE"
  echo "Wrote $ENV_FILE (0600)."
fi

# ---- ExecStart ---------------------------------------------------------------
if [ "$WRAP_INFISICAL" = y ]; then
  EXECSTART="$(command -v infisical) run --env=$INFISICAL_ENV --silent -- $BIN"
  echo
  echo "Service will start via:  infisical run --env=$INFISICAL_ENV -- optimimer-backend"
  echo "For headless auth, give it a machine identity token — e.g. add a drop-in:"
  echo "  sudo systemctl edit $APP   # then:  [Service]  Environment=INFISICAL_TOKEN=<token>"
else
  EXECSTART="$BIN"
fi

# ---- systemd unit ------------------------------------------------------------
echo "Installing systemd service ($SERVICE)…"
sudo tee "$SERVICE" >/dev/null <<EOF2
[Unit]
Description=Optimimer backend (Telegram bot + scheduler)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$RUN_USER
WorkingDirectory=$DIR
EnvironmentFile=-$ENV_FILE
ExecStart=$EXECSTART
Restart=always
RestartSec=5
NoNewPrivileges=true
# Raw-socket capability for Wake-on-LAN (etherwake). Ambient caps are
# inherited by child processes and coexist with NoNewPrivileges — no sudo.
AmbientCapabilities=CAP_NET_RAW

[Install]
WantedBy=multi-user.target
EOF2

sudo systemctl daemon-reload
sudo systemctl enable "$APP" >/dev/null 2>&1 || true
sudo systemctl restart "$APP"
sleep 1
sudo systemctl --no-pager status "$APP" | head -10 || true

# ---- optional: Obsidian Headless sync unit -----------------------------------
# If `ob` (obsidian-headless) is installed and logged in, offer to run the vault
# sync as a service for this user. Template: deploy/obsidian-sync.service.
if command -v ob >/dev/null 2>&1 && [ -f "$DIR/obsidian-sync.service" ] && [ ! -f /etc/systemd/system/obsidian-sync.service ]; then
  read -r -p "obsidian-headless found. Install the vault sync service for $RUN_USER? [y/N] " a </dev/tty
  if [[ "${a:-}" =~ ^[Yy] ]]; then
    sed "s|@USER@|$RUN_USER|g; s|@HOME@|$HOME|g; s|@VAULT@|${VAULT_DIR:-$DIR/vault}|g; s|@OB@|$(command -v ob)|g" \
      "$DIR/obsidian-sync.service" | sudo tee /etc/systemd/system/obsidian-sync.service >/dev/null
    sudo systemctl daemon-reload
    sudo systemctl enable --now obsidian-sync >/dev/null 2>&1 || true
    echo "obsidian-sync service installed (run 'ob sync-setup' first if you haven't)."
  fi
fi

echo
echo "Done. Follow logs with:  journalctl -u $APP -f"
echo
echo "Next: open your bot in Telegram and send this setup code to pair as the owner:"
echo
echo "      $SETUP_CODE"
echo
echo "(It works once. If you lose it: grep OPTIMIMER_SETUP_CODE $ENV_FILE, or check the service log.)"
